### ISSUE TITLE
Consistent options object usage

### ISSUE THREAD

**Issue by ejcoyle88** [nhunt88/ekm-newsletter-modal#1]
You should use the options object that is being passed into the function, rather than the global one here. :)

`CreateCookieFixed(newsletterDisplayedKey, isDisplayed, newsletterOptions)`
to
`CreateCookieFixed(newsletterDisplayedKey, isDisplayed, options)`

https://github.com/nhunt88/ekm-newsletter-modal/blob/master/newslettermodal.js#L43

**Comment by nhunt88** [comment]
Should be resolved by merge
